import { PERSONAS } from "../data/personas.js";

function escapeHtml(text) {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

export function exportHtml({ messages, topic, turnCount, maxTurns }) {
  const bubbles = messages
    .map((msg) => {
      const persona = PERSONAS[msg.side];
      const isLeft = msg.side === "left";
      return `
      <div style="display:flex;justify-content:${isLeft ? "flex-start" : "flex-end"};margin-bottom:16px;">
        <div style="max-width:85%;padding:14px 18px;border-radius:${isLeft ? "4px 16px 16px 16px" : "16px 4px 16px 16px"};background:${persona.bubbleBg};border:1px solid ${persona.accent}22;">
          <div style="font-size:11px;color:${persona.accent};font-weight:600;margin-bottom:6px;letter-spacing:1px;text-transform:uppercase;">
            ${persona.emoji} ${escapeHtml(persona.name)}
          </div>
          <div style="font-size:14px;line-height:1.6;color:#d4d4d4;">${escapeHtml(msg.text)}</div>
        </div>
      </div>`;
    })
    .join("\n");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Claude vs Claude — ${escapeHtml(topic)}</title>
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;600;700&display=swap" rel="stylesheet" />
  <style>
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      min-height: 100vh;
      background: #0a0a0f;
      color: #e0e0e0;
      font-family: 'JetBrains Mono', 'Fira Code', monospace;
    }
  </style>
</head>
<body>
  <!-- Header -->
  <header style="text-align:center;padding:30px 20px 10px;">
    <h1 style="font-size:28px;font-weight:700;letter-spacing:-1px;">
      <span style="color:#4fc3f7;">Claude</span>
      <span style="color:#555;margin:0 8px;font-weight:400;">vs</span>
      <span style="color:#ef5350;">Claude</span>
    </h1>
    <p style="font-size:12px;color:#555;margin-top:4px;letter-spacing:2px;text-transform:uppercase;">AI Debate Arena</p>
  </header>

  <!-- Content -->
  <main style="max-width:960px;margin:0 auto;padding:0 20px 40px;">
    <!-- Topic banner -->
    <div style="text-align:center;padding:10px 20px;margin-bottom:20px;background:rgba(255,255,255,0.03);border-radius:8px;border:1px solid rgba(255,255,255,0.06);">
      <span style="font-size:11px;color:#555;letter-spacing:2px;text-transform:uppercase;">Topic:</span>
      <span style="color:#ccc;font-size:14px;"> ${escapeHtml(topic)}</span>
      <span style="color:#444;font-size:12px;margin-left:12px;">Round ${turnCount}/${maxTurns}</span>
    </div>

    <!-- Messages -->
    ${bubbles}
  </main>

  <!-- Footer -->
  <footer style="text-align:center;padding:20px;border-top:1px solid rgba(255,255,255,0.06);">
    <p style="font-size:12px;color:#555;">
      Generated by <a href="https://claude-vs-claude.vercel.app" style="color:#4fc3f7;text-decoration:none;">Claude vs Claude</a>
    </p>
  </footer>
</body>
</html>`;
}
